#!/bin/bash
# Manual deployment instructions for GCP VM
# Run these commands directly on your GCP VM via the console

echo "🚀 Manual Deployment Instructions for GCP VM"
echo "============================================="
echo ""
echo "1. Connect to your GCP VM via the console:"
echo "   https://console.cloud.google.com/compute/instances"
echo "   Click 'SSH' next to your VM instance"
echo ""
echo "2. Run these commands in order:"
echo ""
echo "# Navigate to project directory"
echo "cd /home/tejaswinrenugunta/options-scanner"
echo ""
echo "# Stop existing processes"
echo "sudo pkill -f gunicorn || echo 'No gunicorn processes found'"
echo ""
echo "# Update code"
echo "git stash || echo 'No changes to stash'"
echo "git pull origin main"
echo ""
echo "# Activate virtual environment"
echo "source venv/bin/activate"
echo ""
echo "# Install any new dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Start the application"
echo "nohup gunicorn --bind 0.0.0.0:8080 --workers 5 --timeout 120 app:app > gunicorn.log 2>&1 &"
echo ""
echo "# Check if running"
echo "sleep 5"
echo "pgrep -f gunicorn"
echo ""
echo "# Test the API"
echo "curl -s 'http://localhost:8080/api/ticker-prices' | head -50"
echo ""
echo "✅ Your app should now be running with real-time API data!"
echo "🌐 Access at: http://34.28.161.37:8080"
